version: "3"

services:
  flask:
    build: ./app
    container_name: flask
    ports:
      - "3000:3000"
    networks:
      - wehelp_third_network

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - flask
    volumes:
      - ~/alicethirteen.com:/etc/nginx/cert
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST_SSL_CRT=cert/nginx.crt
      - NGINX_HOST_SSL_KEY=cert/nginx.key
    networks:
      - wehelp_third_network

networks:
  wehelp_third_network:
    external: true


