version: "3"

services:
  flask:
    build: ./app
    container_name: flask
    ports:
      - "3000:3000"
    networks:
      - wehelp_third_network

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - flask
    ports:
      - "80:80"
    networks:
      - wehelp_third_network

networks:
  wehelp_third_network:
    external: true


