version: "3"

services:
  flask:
    build: ./app
    container_name: flask
    networks:
      - wehelp_third_network

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - flask
    ports:
      - 80:80
      - 443:443
    networks:
      - wehelp_third_network

networks:
  wehelp_third_network:
    external: true


